### ISSUE TITLE
RTP1 and RTP2 not loading in Kodi PVR Simple iptv

### ISSUE THREAD

**Issue by vitalPixel** [LITUATUI/M3UPT#68]
Hi @LITUATUI, thanks for the great work maintaining this list.

for a few weeks now, RTP1 and RTP2 do not load when I’m using the kodi PVR simple iptv add-on.
Looking at the logs reveals an Error 429 (something to do with rate limits?).

Every other channel is working fine and these 2 also work on other players, I just have issues on kodi.

I’m in Portugal, with a Portuguese IP.

Any ideas on how to solve this?

**Comment by LITUATUI** [comment]
Thanks for the heads up, it's fixed now.

**Comment by vitalPixel** [comment]
Thanks @LITUATUI but it’s still not working for me… in fact, now RTP3, which used to work fine, also stopped working :/

Other channels like Porto Canal, SIC, etc seem fine though.

**Comment by LITUATUI** [comment]
Just tested Kodi on my Linux laptop, all RTP channels are working.

**Comment by manuelpinto95** [comment]
I'm still encountering this issue with Kodi on Android TV on two different TV's, including at another house, different IP. @LITUATUI  could you share what the version of Kodi and the simple IPTV addon you have? Could be related to that.

**Comment by vitalPixel** [comment]
Same for me but on a raspberry pi 3.

I’ve also tried changing some simple IPTV settings related to cache and user agent (following suggestions from elsewhere on the interwebs) but with no success…

**Comment by LITUATUI** [comment]
I'm using Kodi 20.5 with IPTV Simple Client 20.13.0 on EndeavourOS (Arch).


![Kodi-2](https://github.com/LITUATUI/M3UPT/assets/49299328/0245e061-3495-414d-b3c1-1b29a7d95c1d)
![Kodi-1](https://github.com/LITUATUI/M3UPT/assets/49299328/e3b60f0b-8afc-48c7-964b-3376524a07de)

**Comment by helio022** [comment]
Did anyone found a solution the only Portuguese channels working for me is sic and tvi ficcao

**Comment by LITUATUI** [comment]
Guys, I need more info, your OS, Kodi version, addon version and log.

**Comment by helio022** [comment]
![20240327_190204](https://github.com/LITUATUI/M3UPT/assets/165179872/cd97ec3e-db2c-4602-9a00-6b76a8fc4fac)
![20240327_190250](https://github.com/LITUATUI/M3UPT/assets/165179872/9335bb71-3a2d-4932-842a-2140a4dc9be4)

**Comment by vitalPixel** [comment]
@LITUATUI sorry I was away from home the past few days.

I’m on Libreelec 10.0.4 with Kodi 19.5.

Here’s a debug log straight after reboot: https://paste.kodi.tv/ukujozixuk 

Let me know if there’s any other info that can help you.

**Comment by LITUATUI** [comment]
Obrigado, acho que já sei o que é, logo já resolvo.

Penso estar relacionado com os servidores da RTP bloquearem o acesso devido a demasiados downloads simultâneos (principalmente dos logos das rádios e documentários RTP).

A solução passa por sacar os logos e metê-los no GitHub.

**Comment by vitalPixel** [comment]
Maravilha, obrigado... se quiseres que volte a testar mais alguma coisa avisa!

**Comment by LITUATUI** [comment]
Acho que já encontrei o verdadeiro problema [aqui](https://github.com/xbmc/inputstream.adaptive/issues/1511).

A solução passa por desactivar o inputstream.adaptive na lista mas o resultado vai ser um zapping mais lento.

**Comment by vitalPixel** [comment]
Obrigado @LITUATUI , do meu lado está a funcionar 👍🏻
